---
version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hse_medical
      POSTGRES_USER: 123456
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5450:5432